#!/bin/bash

REPO="https://github.com/workshop-blue-products/boltup-lightsail-bitcoin.git"
APP_DIR=/home/ubuntu/
cd $APP_DIR
git clone $REPO

sudo apt-get update
sudo apt-get install supervisor
sudo cp boltup-lightsail-bitcoin/supervisor-bitcoin.conf /etc/supervisor/conf.d/

BTCURL="https://bitcoincore.org/bin/bitcoin-core-24.0.1/bitcoin-24.0.1-x86_64-linux-gnu.tar.gz"
wget $BTCURL -O bitcoin-core.tgz
sudo mkdir /opt/bitcoin
sudo tar -zxvf bitcoin-core.tgz -C /opt/bitcoin --strip-components=1

sudo mkdir /bitcoin

sudo cp boltup-lightsail-bitcoin/bitcoin.conf /etc/
